### ISSUE TITLE
[FEAT]: Problema de claridad y consistencia en Place.json

### ISSUE THREAD

**Issue by Utmite** [open-source-uc/UbiCate-v2#105]
# Problema
Existe floor, floors, category y categories
- [x] consistencia de floor y floors
- [x] consistencia de category y categories

## Comentarios
Pienso que podriamos dejar solo floors y categories

**Comment by SSParzival** [comment]
Concuerdo, eso sería lo ideal.

**Comment by Utmite** [comment]
Voy a proceder a arreglar lo de category
