### ISSUE TITLE
[FEAT]: Botón para compartir sala

### ISSUE THREAD

**Issue by vlermandac** [open-source-uc/UbiCate-v2#109]
# Problema
Al aparecer la información de una sala, que haya un botón que permita compartir la ubicación de esta.

## Objetivos

- En desktop, basta con que se copie el enlace del url que lleva a la sala.
- En móvil, sería bueno ser capaz de invocar el popup del sistema que permite copiar o compartir a través de alguna app.

**Comment by Utmite** [comment]
Podríamos poner un botón de share en el menú informativo
