### ISSUE TITLE
[FEAT]: agregar pill: agua y auditorios

### ISSUE THREAD

**Issue by Utmite** [open-source-uc/UbiCate-v2#125]
# Problema
No existe el pin agua y auditorios

**Comment by vlermandac** [comment]
lo tengo casi

**Comment by Utmite** [comment]
¿Se podría hacer que se generen automáticamente por cada categoría que hay en types.ts, así al agregar una nueva categoría no habría que hacer un nuevo pill?

**Comment by Benjamin-Ch** [comment]
lo puedo hacer yo?
