### ISSUE TITLE
[BUG]: se renderizan todos los pill, aunque no estén en pantalla 

### ISSUE THREAD

**Issue by Utmite** [open-source-uc/UbiCate-v2#126]
Al usar un pill se muestran todos los puntos de esa categoría, y en el caso de las salas genera lag

Solución:
Solo se muestren los pills de la zona que el usuario este observando.

**Comment by mc-cari** [comment]
Una solución es reducir la cantidad de puntos que uno esta observando.

Se perderia un poco de detalle pero no importa mucho porque los nombres no se sobrelapan (layer `placesTextLayer`) y no se muestran todos actualmente.

Habría que probar entre 2 opciones:

- Agregar los puntos a una layer de símbolos para que actuen igual que el texto y no se sobrelapen. Luego agregar un listener [onClick](https://stackoverflow.com/questions/48931142/interaction-with-thousands-of-markers-or-geojson-points-on-mapbox-android) para abrir sus menus (así funciona google maps, solo la gente tiene que hacer zoom para darse cuenta que hay más salas).
- Clusterizar los puntos y decidir que nombre colocarle a cada cluster. El nombre de cluster puede ser "salas B, salas A" si tiene salas de ambos. Suena más complicado de implementar pero podría ayudar enterarse de que en cierta parte uno puede encontrar este tipo de salas y no simplemente desaparecer como la opción anterior.

**Comment by Utmite** [comment]
Creo que la mejor opción es la 2da, pues normalmente la salas con igual letra está en la misma parte, además así están presentadas en los mapas oficiales de la u

**Comment by Utmite** [comment]
Creo que la mejor opción es la 2da, pues normalmente la salas con igual letra está en la misma parte, además así están presentadas en los mapas oficiales de la uc

**Comment by mc-cari** [comment]
Verdad, creo que otra forma de implementar la segunda opción evitando clustering es definiendo 2 layer distintas, la primera layer es la actual con todas las salas solo visible cuando hay harto zoom y la segunda layer que es solo de letras/edificios ("salas A") cuando el zoom es bajo. Usando [maxzoom](https://docs.mapbox.com/style-spec/reference/layers/#maxzoom).

**Comment by Utmite** [comment]
Me gusta esa solución

**Comment by mc-cari** [comment]
Ahí esta complicado, habria que dejarlo como marker a parte. Además hay que ver como van a seguir funcionando los filtros. Creo que hay que jugar un poco con layers para aprender y ver si se puede.

**Comment by Utmite** [comment]
Los layers no funcionan bien con SVG, el escalado queda horrible. Mejor quitemos el pill de las salas xd
