### ISSUE TITLE
[FEAT]: Boton de issues

### ISSUE THREAD

**Issue by Benjamin-Ch** [open-source-uc/UbiCate-v2#128]
# Problema
Como usuario no registrado en github, quiero poder notificar de errores o mejoras a la aplicacion.

## Objetivos

- [x] Botón de issues en la web

## Comentarios
Enfocarlo en publico en general.

**Comment by Utmite** [comment]
La notificación de tu issue será complicado, pues Ubicate no tiene un sistema de usuarios

**Comment by SSParzival** [comment]
Quizás sea buena idea dejar este github de una forma más visible y clara en la página web, y remarcar el hecho de plantear issues para la mejora de UbiCate.

**Comment by Utmite** [comment]
Si, eso es aún más rápido, dejar que existe el repo para reportar problemas como provisorio y luego a futuro hacer un form de reporte
