### ISSUE TITLE
[BUG]: Bug en las pill y no se mantiene el param campus

### ISSUE THREAD

**Issue by Utmite** [open-source-uc/UbiCate-v2#140]
# Describe el bug
Al apretar un pin no se cambia el parámetro campus

## Pasos para generar el bug
Ir al mapa y apretar un pin

**Comment by Utmite** [comment]
Sería conveniente crear una función, ya que la lógica para cambiar los parámetros está duplicada en varias partes

**Comment by Utmite** [comment]
imposible, hay que cambiar muchas cosas por un detalle pequeño xd

**Comment by Utmite** [comment]
Solo arregle el de pills

**Comment by mc-cari** [comment]
Si estan complicados los parámetros por ahora. Seguiría la regla de que los param no sean redundantes si es que te parece: Con solo el place se puede inferir el campus, así que no habría que guardar el campus como param.
