### ISSUE TITLE
[FEAT]:  Agregar funcionalidad de hover y click a los marcadores resultados del geocoder

### ISSUE THREAD

**Issue by mc-cari** [open-source-uc/UbiCate-v2#24]
# Problema
Agregar información adicional a los marcadores resultantes del geocoder

## Objetivos

- [x] Añadir información al hacer hover al marcador
- [x] Añadir información al hacer click al marcador

**Comment by MrBased** [comment]
Tener en cuenta que en celular el hover y su popup ya se comporta como click, es decir, al tocar (no mantener) una ubicación aparece el popup del hover y se quita cuando te toca otra parte de la pantalla

**Comment by mc-cari** [comment]
Vale, se podría dejar el nombre al lado del marcador como en google maps para reemplazar el hover y dejar solo el click.

**Comment by Utmite** [comment]
Holi, creo que lo mejor es copiar la idea de Google. En PC, que aparezca un menú lateral y en celular, un menú en la parte inferior.
