### ISSUE TITLE
[FEAT]: DISCUSIÓN: input de marker en vez de posición actual

### ISSUE THREAD

**Issue by diegocostares** [open-source-uc/UbiCate-v2#30]
# Problema
Por telegram @benjavicente sugirió utilizar un input en el mapa en vez de que se use la ubicación actual en el formulario, hay que discutir la idea para ver si hay tiempo para implementarlo y si nos sirve.

La funcionalidad vendría siendo realizada con [drag-a-marker](
https://docs.mapbox.com/mapbox-gl-js/example/drag-a-marker/)

**Comment by mc-cari** [comment]
Implementado en una [PR](https://github.com/open-source-uc/UbiCate-v2/pull/33).
