### ISSUE TITLE
[BUG]: Mapa no carga

### ISSUE THREAD

**Issue by mc-cari** [open-source-uc/UbiCate-v2#35]
En la página del mapa se muestra un fondo blanco en lugar del mapa, sin ningún mensaje de error.

Pasos para replicar el comportamiento:
1. Ir a la ruta "/map"
2. Ver fondo blanco

Ocurrió en la versión del la página mostrada en la feria de iniciativas DCC, revise y la key de Mapbox no es el origen del error.

**Comment by MrBased** [comment]
el cambio de h-screen a h-full para que el formulario se vea mejor causó eso
 https://github.com/open-source-uc/UbiCate-v2/blob/f830563035951d1403127c17b93b47f70e919d5e/app/layout.tsx#L25
