### ISSUE TITLE
Buscar: Baño | Todos

### ISSUE THREAD

**Issue by Utmite** [open-source-uc/UbiCate-v2#75]
# Problema
Actualmente, al buscar "baño" solo se muestra un baño en el resultado, lo cual no es ideal cuando no estoy cerca de la ubicación. Sería más útil tener una opción como "Baño | Todos" o "Baño" y que se muestren todos los baños registrados en la app.

**Comment by mc-cari** [comment]
Si, para buscar por categoria como "baño" vamos a añadir pills de búsqueda, un botón en el mapa que diga "baños" y muestre todos los baños registrados. Esto solucionaría el problema?

**Comment by Utmite** [comment]
Si era eso
