### ISSUE TITLE
[BUG]: Mapa se crashea al cambiar de campus

### ISSUE THREAD

**Issue by MrBased** [open-source-uc/UbiCate-v2#78]
# Problema
Se crashea el mapa al saltar de campus en campus a través del menú del sidebar.

## Pasos para generar el bug
Pasos para reproducir el comportamiento:
1. Seleccionar campus en el sidebar
2. Seleccionar otro campus
3. Se crashea al seleccionar otro campus por segunda/tercera vez

## Contexto adicional
Viene a partir de esta función que creé para darle el listener al geocoder para un mismo evento. Sin embargo, me parece que nunca le dí ese uso y podría ser perfectamente eliminado. Partir probando con eso primero. 
**Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'remove')**
https://github.com/open-source-uc/UbiCate-v2/blob/ed412e64deb638726f3defca7ef9dab056ee65cc/utils/geocoderEvents.tsx#L6-L8

**Comment by vlermandac** [comment]
Ahora hay un nuevo bug donde las pills no se pueden desmarcar una vez se cambia de campus. No sé si crear un nuevo issue o seguirlo aquí. La solución más directa sería que al cambiar de campus se borren las pills.
