### ISSUE TITLE
[FEAT]: Mover tareas de Trello a issues de GitHub

### ISSUE THREAD

**Issue by mc-cari** [open-source-uc/UbiCate-v2#81]
# Problema

Traer las tareas e ideas desde [Trello](https://trello.com/b/uqwtrrZN/tareas) para que sean más accesibles para cualquier persona que quiera aportar.

**Comment by vlermandac** [comment]
Issues creadas y aquellas ideas que no estaban tan desarrolladas las agregué a una nueva discusión de ideas #112 🙂‍↕️
