### ISSUE TITLE
[FEAT]: Inclusión de puntos de abastecimiento de agua

### ISSUE THREAD

**Issue by Benjamin-Ch** [open-source-uc/UbiCate-v2#91]
Hola,
He estado utilizando Ubicate para localizar los puestos de comida y me ha sido de gran ayuda. Sin embargo, creo que sería útil contar también con la opción de visualizar los puntos de abastecimiento de agua, ya que actualmente no sé dónde se encuentran y esto sería muy práctico para los usuarios.

**Comment by SSParzival** [comment]
Concuerdo, opino que esto debería replicarse exponencialmente.

**Comment by Utmite** [comment]
Traslado a #122
