### ISSUE TITLE
[FEAT]: Implementar Fuzzy Search para el buscador

### ISSUE THREAD

**Issue by SSParzival** [open-source-uc/UbiCate-v2#93]
# Problema
Solicito que la búsqueda use regex. 
Sería una buena idea.
10/10.

## Comentarios

Agregar comentarios adicionales.

**Esta tu feature relacionada a un problema? Por favor describe cual es.**
Un pequeña y clara descripción del problema. Ex. Siempre me frustro cuando [...]

**Describe la solución que te gustaría**
Una pequeña y concisa descripción de que te gustaría que pasara

**Describe posibles soluciones que consideraste**
Una pequeña y concisa descripción de cualquier solución que te imaginaras.

**Comment by vlermandac** [comment]
Fuzzy Search hace lo que tienes en mente. Buena idea
